# Generated by Django 5.2.11 on 2026-06-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='asssigned_at',
            new_name='assigned_at',
        ),
    ]
