# Generated by Django 5.2.11 on 2026-06-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experince',
            new_name='experience',
        ),
    ]
